### ISSUE TITLE
インタラクティブの問題が含まれているときのエラー

### ISSUE THREAD

**Issue by harurunrunrun** [take0x/accprob#5]
インタラクティブの問題のテストケース取得時にエラーを吐いて以降の問題のテストケースが取得できない

**Comment by take0x** [comment]
ご報告ありがとうございます。
具体的な再現手順をお教えいただけますと幸いです。

**Comment by n4okins** [comment]
例えば`accprob n https://kenkoooo.com/atcoder/#/contest/show/07cc74a1-098e-4c51-9ac5-6121276d3c11`
では、84番目の`https://atcoder.jp/contests/typical90/tasks/typical90_ba`のダウンロードに失敗します。
`oj t/r`コマンドでできるらしい（`https://github.com/online-judge-tools/oj/blob/master/docs/getting-started.ja.md#リアクティブ問題`）ですが当方の環境では権限周りがうまくいかず……

**Comment by take0x** [comment]
修正しました。
お二人ともありがとうございました。
